### ISSUE TITLE
Currently able to bypass a log-out through the phones back-button.

### ISSUE THREAD

**Issue by OlofSjogren** [OlofSjogren/GoAyo#101]
If you log out and then press the back-button on your phone, you will return to the groups menu of the previously logged in user. 
The same goes for the inverse where you can return to the log in screen by pressing the back button instead of the log out button.

Make it so that you can not switch between these fragments/activities using the phones back button.

**Comment by Puh00** [comment]
@OlofSjogren Working on it.

I am not able to recreate the bug where you can navigate back to log in screen from MainActivity?

**Comment by Puh00** [comment]
Shouldn't even be possible to return to the log in screen from MainActivity since the LoginActivity is finished when navigating to MainActivity after successful login
